# Generated by Django 2.2.1 on 2019-06-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='city_phone',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='ip_phone',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
