# Generated by Django 2.2.1 on 2019-06-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='timezone',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
