# Generated by Django 2.2.3 on 2019-07-07 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='room',
        ),
    ]
