# Generated by Django 2.2.1 on 2019-05-19 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0002_person_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch_office',
            name='branch_office_number',
        ),
        migrations.AddField(
            model_name='branch_office',
            name='branch_office_region_number',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='branch_office',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='phonebook.Branch_Office'),
        ),
        migrations.AlterField(
            model_name='person',
            name='department',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='phonebook.Department'),
        ),
        migrations.AlterField(
            model_name='person',
            name='position',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='phonebook.Position'),
        ),
    ]
