# Generated by Django 2.2.3 on 2019-07-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0002_remove_person_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='room',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
